name: ✨ Feature Request
description: Suggest a new feature or enhancement for VPNCTL
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information about your idea.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Brief summary of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        Describe the problem or use case:
        - As a user, I want to...
        - Currently, I have to...
        - This would help with...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Describe your proposed solution:
        - The feature should...
        - It would work by...
        - Users would interact with it via...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of VPNCTL would this feature affect?
      options:
        - CLI interface
        - TUI interface
        - Configuration system
        - VPN connection management
        - DNS management
        - Profile management
        - Logging/monitoring
        - Installation/setup
        - Documentation
        - Testing
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my usage
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered or are currently using?
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...
        - Current workaround: ...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how this feature would be used (commands, config, etc.)
      placeholder: |
        # Example command usage
        vpnctl new-feature --option value
        
        # Example configuration
        [new_section]
        option=value
      render: shell
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Any ideas about how this could be implemented? (Optional - no coding required!)
      placeholder: |
        - Could use library X for...
        - Might need to modify component Y...
        - Similar to feature Z in project...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples that would help understand this feature
      placeholder: Add any other context, links to similar features, mockups, etc...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have checked the project roadmap and documentation
          required: true
        - label: I would be willing to help test this feature
          required: false
        - label: I would be interested in contributing to this feature
          required: false